USE EXAMEN_03;

 -- Insertar Registro de Administradores

 INSERT INTO TBL_ADMINISTRADOR(DSC_NOMBRE,DSC_USUARIO,DSC_PASSWORD) VALUES("Eduardo Sequeira","esequeira","Admin123");
 INSERT INTO TBL_ADMINISTRADOR(DSC_NOMBRE,DSC_USUARIO,DSC_PASSWORD)  VALUES("Jose Carlos Alavez","jcAlavez","Admin456");
 INSERT INTO TBL_ADMINISTRADOR(DSC_NOMBRE,DSC_USUARIO,DSC_PASSWORD) VALUES("Maria Perez","mperez","Admin789");
 INSERT INTO TBL_ADMINISTRADOR(DSC_NOMBRE,DSC_USUARIO,DSC_PASSWORD) VALUES("Anthony Vega","avega","Admin963");

 -- INSERT INTO TBL_USUARIO(DSC_NOMBRE_COMPLETO,DSC_USUARIO,DSC_PASSWORD,DSC_PAIS,DSC_CORREO,DSC_TELEFONOS)
 -- VALUES("Aaron Ramirez","aramirez","user123","Costa Rica","aramirez@noesis.com","2237-95-61 / 88-55-66-11");


  -- INSERT INTO TBL_COMPRA (COD_USUARIO,COD_PRODUCTO) VALUES (1,2);


  -- INSERT INTO TBL_PRODUCTO(COD_ID,DSC_NOMBRE,DSC_DESCRIPCION,DSC_COSTO,DSC_CANTIDAD) VALUES(001,"Computadora","Portatil Personal DELL",500000,10);

  -- INSERT INTO TBL_PRODUCTO(COD_ID,DSC_NOMBRE,DSC_DESCRIPCION,DSC_COSTO,DSC_CANTIDAD,DSC_POPULARIDAD) VALUES(001,"Computadora","Portatil Personal DELL",500000,10,0);

  -- INSERT INTO TBL_PRODUCTO(COD_ID,DSC_NOMBRE,DSC_DESCRIPCION,DSC_COSTO,DSC_CANTIDAD,DSC_POPULARIDAD) VALUES(002,"Libro","Java Interfacez",25000,5,0);


  -- UPDATE TBL_PRODUCTO  SET DSC_CANTIDAD = 7  WHERE COD_ID = 1134;



 -- SELECT COD_ID, DSC_NOMBRE, DSC_USUARIO, DSC_PASSWORD  FROM TBL_ADMINISTRADOR WHERE DSC_USUARIO = "bhernandez"  AND DSC_PASSWORD = "Admin123" ;


 -- SELECT COD_ID, DSC_NOMBRE_COMPLETO, DSC_USUARIO, DSC_PASSWORD, DSC_PAIS, DSC_CORREO, DSC_TELEFONOS FROM examen_03.TBL_USUARIO WHERE DSC_USUARIO ="" AND DSC_PASSWORD ="";